import { defineStore } from 'pinia'

export const useThemeStore = defineStore('theme', () => {
  // 主題配置映射表
  const themes = {
    cuisine: {
      id: 'cuisine',
      name: '美食饗宴',
      image:
        'https://tb-static.uber.com/prod/image-proc/processed_images/1b22e7fa06c151ff897f79eeb6717c72/3ac2b39ad528f8c8c5dc77c59abb683d.jpeg',
      categoryId: 'restaurant', // 對應到餐廳分類
      stores: [
        {
          id: 1,
          name: '築間幸福鍋物',
          category: '美食 > 火鍋',
          rating: 4.5,
          distance: '1.2km',
          image: '/theme/hotpot.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 2,
          name: '欣葉台菜',
          category: '美食 > 台菜',
          rating: 4.8,
          distance: '2.5km',
          image: '/theme/food.jpeg',
          coupon: '滿千送百購物金',
        },
        {
          id: 3,
          name: '饗食天堂',
          category: '美食 > 吃到飽',
          rating: 4.3,
          distance: '3.1km',
          image: '/theme/paradise.jpeg',
          coupon: '會員專屬折扣券',
        },
        {
          id: 4,
          name: '鼎泰豐',
          category: '美食 > 小籠包',
          rating: 4.7,
          distance: '1.8km',
          image:
            'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=300&h=200&fit=crop',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 5,
          name: '瓦城泰式料理',
          category: '美食 > 泰式料理',
          rating: 4.4,
          distance: '2.2km',
          image: 'https://i.pinimg.com/1200x/03/3f/cc/033fcc670a1e1833fc1ca94847c59366.jpg',
          coupon: '滿千送百購物金',
        },
        {
          id: 6,
          name: '藏壽司',
          category: '美食 > 日式料理',
          rating: 4.5,
          distance: '1.5km',
          image:
            'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
        {
          id: 7,
          name: '添好運',
          category: '美食 > 港式飲茶',
          rating: 4.6,
          distance: '2.8km',
          image:
            'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=300&h=200&fit=crop',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 8,
          name: '三井日本料理',
          category: '美食 > 日式料理',
          rating: 4.8,
          distance: '3.5km',
          image:
            'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
      ],
    },
    dessert: {
      id: 'dessert',
      name: '美味甜點',
      image: '/theme/dessert.jpeg',
      categoryId: 'coffee', // 對應到咖啡飲品分類
      stores: [
        {
          id: 9,
          name: 'Lady M',
          category: '甜點 > 蛋糕',
          rating: 4.6,
          distance: '0.8km',
          image: '/theme/ladym.jpeg',
          coupon: '第二件半價券',
        },
        {
          id: 10,
          name: 'Häagen-Dazs',
          category: '甜點 > 冰淇淋',
          rating: 4.5,
          distance: '1.5km',
          image: '/theme/haagen.jpeg',
          coupon: '滿額現金回饋券',
        },
        {
          id: 11,
          name: '春水堂',
          category: '甜點 > 珍珠奶茶',
          rating: 4.4,
          distance: '1.1km',
          image: '/theme/bubble.jpeg',
          coupon: '會員專屬折扣券',
        },
        {
          id: 12,
          name: '85度C',
          category: '甜點 > 蛋糕',
          rating: 4.2,
          distance: '0.9km',
          image:
            'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=300&h=200&fit=crop',
          coupon: '第二件半價券',
        },
        {
          id: 13,
          name: 'Mister Donut',
          category: '甜點 > 甜甜圈',
          rating: 4.3,
          distance: '1.3km',
          image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=300&h=200&fit=crop',
          coupon: '滿額現金回饋券',
        },
        {
          id: 14,
          name: 'Cold Stone',
          category: '甜點 > 冰淇淋',
          rating: 4.4,
          distance: '1.7km',
          image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
        {
          id: 15,
          name: '星巴克',
          category: '甜點 > 咖啡',
          rating: 4.5,
          distance: '0.5km',
          image:
            'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&h=200&fit=crop',
          coupon: '第二杯半價券',
        },
        {
          id: 16,
          name: 'Godiva',
          category: '甜點 > 巧克力',
          rating: 4.7,
          distance: '2.1km',
          image:
            'https://images.unsplash.com/photo-1606312619070-d48b4bc98e75?w=300&h=200&fit=crop',
          coupon: '滿額現金回饋券',
        },
      ],
    },
    coffee: {
      id: 'coffee',
      name: '咖啡飲品',
      image: '/theme/coffee.jpg',
      categoryId: 'coffee',
      stores: [
        {
          id: 17,
          name: '星巴克',
          category: '飲品 > 咖啡',
          rating: 4.2,
          distance: '0.5km',
          image: '/theme/starbucks.jpeg',
          coupon: '第二杯半價券',
        },
        {
          id: 18,
          name: '路易莎',
          category: '飲品 > 咖啡',
          rating: 4.4,
          distance: '0.8km',
          image: '/theme/louisa.jpeg',
          coupon: '會員專屬折扣券',
        },
        {
          id: 19,
          name: 'cama café',
          category: '飲品 > 咖啡',
          rating: 4.3,
          distance: '1.0km',
          image: '/theme/cama.jpeg',
          coupon: '第二杯半價券',
        },
        {
          id: 20,
          name: '85度C',
          category: '飲品 > 咖啡',
          rating: 4.1,
          distance: '0.9km',
          image:
            'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
        {
          id: 21,
          name: '伯朗咖啡',
          category: '飲品 > 咖啡',
          rating: 4.2,
          distance: '1.2km',
          image:
            'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&h=200&fit=crop',
          coupon: '第二杯半價券',
        },
        {
          id: 22,
          name: '丹堤咖啡',
          category: '飲品 > 咖啡',
          rating: 4.0,
          distance: '1.5km',
          image:
            'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
        {
          id: 23,
          name: '西雅圖咖啡',
          category: '飲品 > 咖啡',
          rating: 4.3,
          distance: '1.8km',
          image:
            'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&h=200&fit=crop',
          coupon: '第二杯半價券',
        },
        {
          id: 24,
          name: '怡客咖啡',
          category: '飲品 > 咖啡',
          rating: 4.1,
          distance: '2.0km',
          image:
            'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
      ],
    },
    japanese: {
      id: 'japanese',
      name: '日式料理',
      image: '/theme/japanese.jpg',
      categoryId: 'restaurant',
      stores: [
        {
          id: 25,
          name: '藏壽司',
          category: '日式 > 壽司',
          rating: 4.5,
          distance: '1.8km',
          image: '/theme/kura.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 26,
          name: '一蘭拉麵',
          category: '日式 > 拉麵',
          rating: 4.7,
          distance: '2.0km',
          image: '/theme/ichiran.jpeg',
          coupon: '滿千送百購物金',
        },
        {
          id: 27,
          name: '乾杯燒肉',
          category: '日式 > 燒肉',
          rating: 4.6,
          distance: '1.5km',
          image: '/theme/kanpai.jpeg',
          coupon: '會員專屬折扣券',
        },
        {
          id: 28,
          name: '三井日本料理',
          category: '日式 > 日式料理',
          rating: 4.8,
          distance: '3.5km',
          image:
            'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 29,
          name: '和民',
          category: '日式 > 居酒屋',
          rating: 4.4,
          distance: '2.2km',
          image:
            'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          coupon: '滿千送百購物金',
        },
        {
          id: 30,
          name: '勝博殿',
          category: '日式 > 炸豬排',
          rating: 4.5,
          distance: '1.9km',
          image:
            'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
        {
          id: 31,
          name: '杏子豬排',
          category: '日式 > 炸豬排',
          rating: 4.6,
          distance: '2.1km',
          image:
            'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 32,
          name: '大戶屋',
          category: '日式 > 定食',
          rating: 4.3,
          distance: '1.7km',
          image:
            'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop',
          coupon: '滿千送百購物金',
        },
      ],
    },
    healthy: {
      id: 'healthy',
      name: '健康輕食',
      image: '/theme/healthy.jpg',
      categoryId: 'restaurant',
      stores: [
        {
          id: 33,
          name: 'Subway',
          category: '輕食 > 三明治',
          rating: 4.1,
          distance: '0.6km',
          image: '/theme/subway.jpeg',
          coupon: '第二件半價券',
        },
        {
          id: 34,
          name: 'SaladStop!',
          category: '輕食 > 沙拉',
          rating: 4.3,
          distance: '1.2km',
          image: '/theme/salad.jpeg',
          coupon: '會員專屬折扣券',
        },
        {
          id: 35,
          name: '貳樓',
          category: '輕食 > 早午餐',
          rating: 4.4,
          distance: '1.8km',
          image: '/theme/secondfloor.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 36,
          name: '摩斯漢堡',
          category: '輕食 > 漢堡',
          rating: 4.2,
          distance: '0.8km',
          image:
            'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop',
          coupon: '第二件半價券',
        },
        {
          id: 37,
          name: '麥當勞',
          category: '輕食 > 漢堡',
          rating: 4.0,
          distance: '0.5km',
          image:
            'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
        {
          id: 38,
          name: '肯德基',
          category: '輕食 > 炸雞',
          rating: 4.1,
          distance: '0.7km',
          image:
            'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 39,
          name: '漢堡王',
          category: '輕食 > 漢堡',
          rating: 4.2,
          distance: '1.0km',
          image:
            'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop',
          coupon: '第二件半價券',
        },
        {
          id: 40,
          name: '樂檸漢堡',
          category: '輕食 > 漢堡',
          rating: 4.3,
          distance: '1.3km',
          image:
            'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
      ],
    },
    world: {
      id: 'world',
      name: '異國風味',
      image: '/theme/world.jpg',
      categoryId: 'restaurant',
      stores: [
        {
          id: 41,
          name: '瓦城',
          category: '泰式 > 泰菜',
          rating: 4.5,
          distance: '2.2km',
          image: '/theme/wacity.jpeg',
          coupon: '滿千送百購物金',
        },
        {
          id: 42,
          name: '薄多義',
          category: '義式 > 披薩',
          rating: 4.2,
          distance: '1.6km',
          image: '/theme/pizza.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 43,
          name: '涓豆腐',
          category: '韓式 > 豆腐鍋',
          rating: 4.4,
          distance: '1.9km',
          image: '/theme/korean.jpeg',
          coupon: '會員專屬折扣券',
        },
        {
          id: 44,
          name: 'TGI Fridays',
          category: '美式 > 美式餐廳',
          rating: 4.3,
          distance: '2.5km',
          image: 'https://images.unsplash.com/photo-1552569979-4b5e1c0b0e0e?w=300&h=200&fit=crop',
          coupon: '滿千送百購物金',
        },
        {
          id: 45,
          name: 'Outback',
          category: '美式 > 牛排',
          rating: 4.4,
          distance: '2.8km',
          image: 'https://images.unsplash.com/photo-1552569979-4b5e1c0b0e0e?w=300&h=200&fit=crop',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 46,
          name: 'N.Y. Bagels',
          category: '美式 > 早午餐',
          rating: 4.2,
          distance: '1.4km',
          image: 'https://images.unsplash.com/photo-1552569979-4b5e1c0b0e0e?w=300&h=200&fit=crop',
          coupon: '會員專屬折扣券',
        },
        {
          id: 47,
          name: 'Texas Roadhouse',
          category: '美式 > 牛排',
          rating: 4.5,
          distance: '3.0km',
          image: 'https://images.unsplash.com/photo-1552569979-4b5e1c0b0e0e?w=300&h=200&fit=crop',
          coupon: '滿千送百購物金',
        },
        {
          id: 48,
          name: "Chili's",
          category: '美式 > 美式餐廳',
          rating: 4.3,
          distance: '2.3km',
          image: 'https://images.unsplash.com/photo-1552569979-4b5e1c0b0e0e?w=300&h=200&fit=crop',
          coupon: '平日午餐9折優惠券',
        },
      ],
    },
    home: {
      id: 'home',
      name: '生活家居',
      image:
        'https://accuratemedsupply.com/wp-content/uploads/2022/09/Bathing-and-Grooming-Side-Image.webp',
      categoryId: 'groceries',
      stores: [
        {
          id: 49,
          name: 'HOLA',
          category: '家居 > 生活百貨',
          rating: 4.4,
          distance: '2.58m',
          image: '/theme/hotpot.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 50,
          name: '特力屋',
          category: '家居 > 五金工具',
          rating: 4.1,
          distance: '3.5km',
          image: '/theme/food.jpeg',
          coupon: '滿千送百購物金',
        },
        {
          id: 51,
          name: '生活工廠',
          category: '家居 > 生活雜貨',
          rating: 4.5,
          distance: '1.9km',
          image: '/theme/paradise.jpeg',
          coupon: '會員專屬折扣券',
        },
      ],
    },
    entertainment: {
      id: 'entertainment',
      name: '休閒娛樂',
      image:
        'https://filmzie.com/blog/wp-content/uploads/2024/01/FREE-MOVING-STREAMING-1024x576.jpg',
      categoryId: 'hotel',
      stores: [
        {
          id: 52,
          name: '威秀影城',
          category: '娛樂 > 電影院',
          rating: 4.7,
          distance: '1.6km',
          image: '/theme/hotpot.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 53,
          name: '錢櫃KTV',
          category: '娛樂 > KTV',
          rating: 4.3,
          distance: '2.8km',
          image: '/theme/food.jpeg',
          coupon: '滿千送百購物金',
        },
        {
          id: 54,
          name: '湯姆熊',
          category: '娛樂 > 遊樂場',
          rating: 4.2,
          distance: '3.2km',
          image: '/theme/paradise.jpeg',
          coupon: '會員專屬折扣券',
        },
      ],
    },
    fashion: {
      id: 'fashion',
      name: '時尚服飾',
      image: 'https://s3-media0.fl.yelpcdn.com/bphoto/MXSnI_vXMrLGgN8akqQ2tQ/1000s.jpg',
      categoryId: 'beauty',
      stores: [
        {
          id: 55,
          name: 'UNIQLO',
          category: '服飾 > 休閒服飾',
          rating: 4.6,
          distance: '1.8km',
          image: '/theme/hotpot.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 56,
          name: 'ZARA',
          category: '服飾 > 時尚服飾',
          rating: 4.4,
          distance: '2.2km',
          image: '/theme/food.jpeg',
          coupon: '滿千送百購物金',
        },
        {
          id: 57,
          name: 'NET',
          category: '服飾 > 平價服飾',
          rating: 4.2,
          distance: '1.5km',
          image: '/theme/paradise.jpeg',
          coupon: '會員專屬折扣券',
        },
      ],
    },
    fitness: {
      id: 'fitness',
      name: '運動健身',
      image: 'https://heho.com.tw/wp-content/uploads/2020/08/b16e247cdda9bc0d50947be19d4cd4b5.jpg',
      categoryId: 'fitness',
      stores: [
        {
          id: 58,
          name: 'Nike',
          category: '運動 > 運動用品',
          rating: 4.6,
          distance: '2.1km',
          image: '/theme/hotpot.jpeg',
          coupon: '平日午餐9折優惠券',
        },
        {
          id: 59,
          name: 'Adidas',
          category: '運動 > 運動用品',
          rating: 4.7,
          distance: '4.5km',
          image: '/theme/food.jpeg',
          coupon: '滿千送百購物金',
        },
        {
          id: 60,
          name: 'World Gym',
          category: '健身 > 健身房',
          rating: 4.5,
          distance: '1.2km',
          image: '/theme/paradise.jpeg',
          coupon: '會員專屬折扣券',
        },
      ],
    },
  }

  // 獲取主題列表
  const getThemeList = () => {
    return Object.values(themes).map((theme) => ({
      id: theme.id,
      name: theme.name,
      image: theme.image,
    }))
  }

  // 根據 id 獲取主題數據
  const getThemeById = (id) => {
    return themes[id] || null
  }

  return {
    themes,
    getThemeList,
    getThemeById,
  }
})
